-- Coral does not support UNION; split queries merged in Python
-- Part 4 of 5: Slack messages (handled in Python via agent/slack_coral.py)
--
-- Coral requires per-channel queries:
--   SELECT * FROM slack.messages(channel => '<channel_id>')
-- Do NOT query FROM slack.messages without a channel argument.
