"""Write CLAUDE.md from persisted project context JSON."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_CONTEXT_PATH = Path.home() / ".sorelax" / "project_context.json"


def _bullets(items: list[str]) -> str:
    if not items:
        return "- (none)"
    return "\n".join(f"- {item}" for item in items)


def format_claude_md(context: dict[str, Any], updated_at: str | None = None) -> str:
    ts = updated_at or context.get("updated_at") or datetime.now(timezone.utc).isoformat()
    lines = [
        "# Project context — auto-generated by Sorelax",
        f"Last updated: {ts}",
        "",
        "## Active work",
        _bullets(context.get("active_work", [])),
        "",
        "## Recent commits",
        _bullets(context.get("recent_commits", [])),
        "",
        "## Open PRs",
        _bullets(context.get("open_prs", [])),
        "",
        "## Sprint goal",
        context.get("sprint_goal") or "(unknown)",
        "",
        "## Key decisions",
        _bullets(context.get("key_decisions", [])),
        "",
        "## Relevant Slack threads",
        _bullets(context.get("relevant_slack_threads", [])),
        "",
        "## Architecture docs",
        _bullets(context.get("architecture_docs", [])),
        "",
    ]
    return "\n".join(lines)


def write_claude_md(
    context_path: Path | None = None,
    output_dir: Path | None = None,
) -> Path:
    """Read context JSON and write CLAUDE.md to output_dir (default: cwd)."""
    path = context_path or DEFAULT_CONTEXT_PATH
    if not path.exists():
        raise FileNotFoundError(f"Context file not found: {path}")

    with path.open(encoding="utf-8") as f:
        context = json.load(f)

    out_dir = output_dir or Path.cwd()
    out_file = out_dir / "CLAUDE.md"
    out_file.write_text(format_claude_md(context), encoding="utf-8")
    return out_file


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    print(write_claude_md())
